# Generated by Django 5.0.3 on 2024-03-15 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_remove_profile_img'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='Profile',
        ),
    ]
