# Generated by Django 5.0.3 on 2024-03-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_alter_profile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
